# domain/ports/product_repository.py
#
# Puerto formal del repositorio de productos (Ports & Adapters).

from typing import Protocol, runtime_checkable


@runtime_checkable
class ProductRepositoryPort(Protocol):
    """Contrato formal del repositorio de productos."""

    def get_all(self, tenant_id: str): ...

    def get_by_id(self, product_id: str): ...

    def get_by_barcode(self, tenant_id: str, barcode: str): ...

    def search(self, tenant_id: str, query: str): ...

    def create(self, data: dict): ...

    def update(self, product_id: str, data: dict): ...

    def soft_delete(self, product_id: str): ...

    def count(self, tenant_id: str): ...

    def get_pending_products(self, tenant_id: str): ...

    def add_barcode_history(self, data: dict): ...

    def get_barcode_stats(self, tenant_id: str) -> dict: ...
