from supabase import create_client

SUPABASE_URL = "https://pjgmnowjtijwxrvflfzl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZ21ub3dqdGlqd3hydmZsZnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTYwODYsImV4cCI6MjA5MTA3MjA4Nn0.-7N6wFoq_xucEKHcElnWvgErlJmFUIhXf867I5sDf9M"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)